# Generated by Django 5.1.7 on 2025-03-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_inventory', 'Can view inventory levels'), ('can_update_price', 'Can update product prices'), ('can_manage_stock', 'Can manage stock levels')]},
        ),
    ]
